// This file is auto-generated by scripts/write-build-info.js.
// Do not edit this file manually.
export const BUILD_REVISION = "8b0b389";
export const BUILD_FULL_REVISION = "8b0b3890db2883b08b651cb20c55653bcba1cf81";
export const BUILD_BRANCH = "main";
export const BUILD_WORKTREE_STATE = "dirty";
export const BUILD_LABEL = "main@8b0b389*";
